# Generated by Django 2.0 on 2018-11-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181113_1714'),
        ('blog', '0007_auto_20180224_0212'),
    ]

    operations = [
    ]
